@echo off
REM sqlcmd batch execution script
REM Server: 127.0.0.1
REM Database: hr01
REM Generated by convert_mysql_to_mssql.py

echo Executing hr01_hinfo.sql...
sqlcmd -S 127.0.0.1 -U mochi -P bell0100 -d hr01 -i "C:\home\develop\gitrep\JRADBDump\hr01\mssql\hr01_hinfo.sql" -f 65001
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: hr01_hinfo.sql failed.
    exit /b %ERRORLEVEL%
)
echo hr01_hinfo.sql completed.

echo Executing hr01_jinfo.sql...
sqlcmd -S 127.0.0.1 -U mochi -P bell0100 -d hr01 -i "C:\home\develop\gitrep\JRADBDump\hr01\mssql\hr01_jinfo.sql" -f 65001
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: hr01_jinfo.sql failed.
    exit /b %ERRORLEVEL%
)
echo hr01_jinfo.sql completed.

echo Executing hr01_pinfo.sql...
sqlcmd -S 127.0.0.1 -U mochi -P bell0100 -d hr01 -i "C:\home\develop\gitrep\JRADBDump\hr01\mssql\hr01_pinfo.sql" -f 65001
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: hr01_pinfo.sql failed.
    exit /b %ERRORLEVEL%
)
echo hr01_pinfo.sql completed.

echo Executing hr01_rinfo.sql...
sqlcmd -S 127.0.0.1 -U mochi -P bell0100 -d hr01 -i "C:\home\develop\gitrep\JRADBDump\hr01\mssql\hr01_rinfo.sql" -f 65001
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: hr01_rinfo.sql failed.
    exit /b %ERRORLEVEL%
)
echo hr01_rinfo.sql completed.

echo Executing hr01_routines.sql...
sqlcmd -S 127.0.0.1 -U mochi -P bell0100 -d hr01 -i "C:\home\develop\gitrep\JRADBDump\hr01\mssql\hr01_routines.sql" -f 65001
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: hr01_routines.sql failed.
    exit /b %ERRORLEVEL%
)
echo hr01_routines.sql completed.

echo Executing hr01_trinfo.sql...
sqlcmd -S 127.0.0.1 -U mochi -P bell0100 -d hr01 -i "C:\home\develop\gitrep\JRADBDump\hr01\mssql\hr01_trinfo.sql" -f 65001
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: hr01_trinfo.sql failed.
    exit /b %ERRORLEVEL%
)
echo hr01_trinfo.sql completed.

echo Executing hr01_wk_org.sql...
sqlcmd -S 127.0.0.1 -U mochi -P bell0100 -d hr01 -i "C:\home\develop\gitrep\JRADBDump\hr01\mssql\hr01_wk_org.sql" -f 65001
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: hr01_wk_org.sql failed.
    exit /b %ERRORLEVEL%
)
echo hr01_wk_org.sql completed.

echo All files executed successfully.
